#!/bin/bash

# Enhanced Worktree Creation Script for Wingman Features
# Includes Obsidian documentation setup

set -e

WORKTREE_DIR=".worktrees"
OBSIDIAN_VAULT_PATH="/Users/mini/Documents/Obsidian Vault"  # Adjust this path as needed

if [ -z "$1" ]; then
    echo "Usage: ./scripts/feature-worktree-create.sh <feature-name> [base-branch] [product-name]"
    echo "Example: ./scripts/feature-worktree-create.sh auth-system main wingman"
    exit 1
fi

FEATURE_NAME="$1"
BASE_BRANCH="${2:-main}"
PRODUCT_NAME="${3:-$(basename $(pwd))}"

# Sanitize names
SAFE_FEATURE=$(echo "$FEATURE_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
BRANCH_NAME="feature/$SAFE_FEATURE"

echo "🚀 Creating feature worktree: $FEATURE_NAME"
echo "📁 Product: $PRODUCT_NAME"
echo "🌿 Branch: $BRANCH_NAME"
echo "🏠 Base: $BASE_BRANCH"

# Check if branch already exists
if git show-ref --quiet "refs/heads/$BRANCH_NAME"; then
    echo "⚠️  Branch '$BRANCH_NAME' already exists."
    read -p "Add worktree for existing branch? [y/N]: " response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        git worktree add "$WORKTREE_DIR/$SAFE_FEATURE" "$BRANCH_NAME"
    else
        echo "❌ Cancelled"
        exit 1
    fi
else
    echo "✨ Creating new branch '$BRANCH_NAME' from '$BASE_BRANCH'"
    git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR/$SAFE_FEATURE" "$BASE_BRANCH"
fi

WORKTREE_PATH="$WORKTREE_DIR/$SAFE_FEATURE"

echo "📝 Setting up feature documentation..."

# Create feature documentation in the worktree
mkdir -p "$WORKTREE_PATH/docs/features"

cat > "$WORKTREE_PATH/docs/features/$SAFE_FEATURE.md" << EOF
# $FEATURE_NAME

**Product:** $PRODUCT_NAME  
**Branch:** $BRANCH_NAME  
**Created:** $(date '+%Y-%m-%d %H:%M:%S')

## Overview

Brief description of the $FEATURE_NAME feature.

## Requirements

- [ ] Requirement 1
- [ ] Requirement 2
- [ ] Requirement 3

## Implementation Plan

### Phase 1: Planning
- [ ] Define specifications
- [ ] Create wireframes/mockups
- [ ] Plan architecture

### Phase 2: Development
- [ ] Core implementation
- [ ] Testing
- [ ] Documentation

### Phase 3: Integration
- [ ] Code review
- [ ] Integration testing
- [ ] Deployment preparation

## Technical Notes

### Architecture
- Component/module structure
- Dependencies
- Integration points

### Testing Strategy
- Unit tests
- Integration tests
- End-to-end tests

## Resources

- [Product Documentation](../../README.md)
- [Development Guide](../development.md)
- [Testing Guide](../testing.md)

## Progress Log

### $(date '+%Y-%m-%d')
- Created feature branch and documentation
- Initial setup completed

---
*Feature created with Wingman workflow*
EOF

# Create development checklist
cat > "$WORKTREE_PATH/docs/features/$SAFE_FEATURE-checklist.md" << EOF
# $FEATURE_NAME - Development Checklist

## Pre-Development
- [ ] Requirements gathering complete
- [ ] Design/mockups approved
- [ ] Technical approach defined
- [ ] Dependencies identified

## Development
- [ ] Core logic implemented
- [ ] Error handling added
- [ ] Logging implemented
- [ ] Configuration externalized

## Testing
- [ ] Unit tests written
- [ ] Integration tests added
- [ ] Manual testing completed
- [ ] Edge cases covered

## Documentation
- [ ] Code comments added
- [ ] API documentation updated
- [ ] User documentation written
- [ ] README updated

## Code Quality
- [ ] Code review completed
- [ ] Linting passed
- [ ] Security review done
- [ ] Performance tested

## Integration
- [ ] Merge conflicts resolved
- [ ] CI/CD pipeline passes
- [ ] Staging deployment successful
- [ ] Production ready

---
*Generated by Wingman feature workflow*
EOF

# Commit the documentation
cd "$WORKTREE_PATH"
git add docs/features/
git commit -m "📝 Add feature documentation for $FEATURE_NAME

- Created feature specification
- Added development checklist
- Setup documentation structure"

cd - > /dev/null

echo ""
echo "✅ Feature worktree setup complete!"
echo "📁 Worktree: $WORKTREE_PATH"
echo "🌿 Branch: $BRANCH_NAME"
echo "📝 Documentation: $WORKTREE_PATH/docs/features/"
echo ""
echo "🚀 Next steps:"
echo "   1. cd $WORKTREE_PATH"
echo "   2. Review feature specification"
echo "   3. Start development!"
echo ""
echo "💡 Tip: Use 'git worktree list' to see all active worktrees"
